# Site settings
author: Jessica Leising
title: About me:
header-img: img/home-bg.png
email: jeleisin@gmail.com
copyright_name: Jessica Leising
description: > # this means to ignore newlines until "baseurl:"
  a short memoir 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jbirdyj

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
